name: Historia Finalizada

on:
  push:
    branches:
      - 'feature**'
    
jobs:
  merge-develop-to-feature:
    name: merge develop a la featura
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'Finalizado') }}
    steps:
      - name: Checkout de repositorio
        uses: actions/checkout@v2
      
      - name: Set Git config
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "Github Actions"
      - name: Merge master back to dev
        run: |
            git fetch --unshallow
            git checkout develop
            git pull
            git checkout ${{ github.ref_name }}
            git merge --no-ff develop -m "Auto-merge master back to dev"
  
          
  run-tests:
    name: Correr las pruebas
    needs: merge-develop-to-feature
    runs-on: ubuntu-latest
    steps:
      - name: Configuración de entorno de python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Instalación de librerías y dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Correr pruebas
        id: correr-pruebas
        run: python -m unittest discover -s tests

  merge-develop:
    name: Merge a develop
    needs: run-tests
    runs-on: ubuntu-latest
    steps:  
    - name: Merge a develop
      uses: tukasz/direct-merge-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        source-branch: ${{ github.ref }}
        target-branch: develop
        commit-message: "Release: ${{ github.ref }} mezclada en develop"
      
