name: Historia Finalizada

permissions:
  contents: write

on:
  push:
    branches:
      - 'feature**'
    
jobs:
  merge-develop-to-feature:
    name: merge develop a la featura
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'Finalizado') }}
    steps:
      - name: Checkout de repositorio
        uses: actions/checkout@v2

      - name: Mezclar rama develop en feature
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: develop
          target-branch: ${{ github.ref }}

      - name: Configuración de entorno de python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalación de librerías y dependencias
        run: |
          ls -al
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Correr pruebas
        id: correr-pruebas
        run: python -m unittest discover -s tests 

      - name: Merge a develop
        if: ${{ success() }}
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: ${{ github.ref_name }}
          target-branch: develop
          commit-message: "Release : ${{ github.ref }} mezclada en develop"
