name: Historia Finalizada

on:
  push:
    branches:
      - 'feature**'
    
jobs:
  merge-develop-to-feature:
    name: merge develop a la featura
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'Finalizado') }}
    steps:
      - name: Checkout de repositorio
        uses: actions/checkout@v2
      
      - name: Set Git config
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "Github Actions"
      - name: Merge master back to dev
        run: |
            git fetch --unshallow
            git checkout develop
            git pull
            git checkout ${{ github.ref_name }}
            git merge --no-ff develop -m "Auto-merge master back to dev"

      - name: Configuración de entorno de python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalación de librerías y dependencias
        run: |
          ls -al
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Correr pruebas
        id: correr-pruebas
        run: python -m unittest discover -s tests 

      - name: Merge a develop
        run: |
          git fetch --unshallow
          git checkout develop
          git pull
          git merge --no-ff ${{ github.ref_name }} -m "Auto merge feature to develop"