name: Release

permissions:
  contents: write

on:
  workflow_run:
    workflows: ["Nombre del Workflow que hace el commit"]
    types:
      - completed
    
jobs:
  create-release-branch:
    name: Crear la rama release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout de repositorio
        uses: actions/checkout@v2

      - name: Crear rama release
        run: |
          git checkout -b release/v2.0
          git push -f -u origin release/v2.0

      - name: Configuración de entorno de python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalación de librerías y dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Correr pruebas
        id: correr-pruebas
        run: python -m unittest discover -s tests
  
      - name: Merge a main
        if: ${{ success() }}
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: release/v2.0
          target-branch: main
          